import React, {useContext} from 'react'
import Head from 'next/head'
import Navbar from '../components/navbar'
import Form from '../components/form'
import { TransactionContext } from '../context/TransactionContext'
import Footer from '../components/footer'
import TransactionHistory from '../components/transactionHistory'


const style = {
  main: `select-none flex flex-col min-h-screen w-full justify-between`,
  msg: `text-center mx-auto text-xl`
}

export default function Home() {
  const {currentAccount} = useContext(TransactionContext)

  return (
    <div className={style.main}>
      <Head>
        <title>Uniswap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/uniswap.png" />
      </Head>

      <Navbar/>
      {currentAccount ? (
        <>
        <Form/>   
        <TransactionHistory/>
        </>
                ) : (
                <div className={style.msg}>Please connect metamask wallet to continue.</div>
                )}
      <Footer/>

    </div>
  )
}
